== C++ Programming from Udacity

=== Notes

=== C++ Nano Degree
==== Title: C++ Programming


=== Lesson 

This section of the catalog contains information regarding The *_Eastern FHIR Coders_* team members from _Georgia Institute of Technology_.
|===
|Author | Ramon Darwin Garcia
|Email  | rdgt07@gmail.com
| Website
| www.webtekton.com
| Darwin Garcia, Developer / Project Manager
| rgarcia47@gatech.edu
|===


=== To Read a File

=== To run a C++ Program in CLI
====
1. Compile the code:
`g++ -std=c++17 file_name.cpp -o file_name`
2. Run the code:
`./file_name`
====

====
 
That's it! To recap, there are essentially four steps to reading a file:

1. `#include <fstream>`
2. Create a `std::ifstream` object using the path to your file.
3. Evaluate the `std::ifstream` object as a bool to ensure that the stream creation did not fail.
4. Use a while loop with getline to write file lines to a string.

====
.Reading a File
[source,C++]
----

//declare a fucntion

void ReadBoardFile(string file_path){
    //declare a object to hold the file
    ifstream store_file;
    //open the file
    store_file.open(file_path);
    //evaluate the object as a bool to ensure tha the file did not fail
    if(store_file){
        //declare a string variable to hold each line of the file
        string line;
        //use a while loop with getline(path,line)
        while(getline(store_file, line)){
            cout << line << "\n";
        }
    }
}
----

=== About the application: 
.The SDOM Questionnaire application is used to 
* Create an electronic form which can be either pushed out to patients ahead
of their appointments or filled out immediately prior to being seen.
* Display data over time to display to a clinician to assist in the treatment decision.
* Populate data warehouse to allow for aggregate data analysis by disease and
drug treatment.

=== Overall Application Flow:
* The patient uses the _Patient portal_ to first authenticate and login to the SDOM Questionnaire page. The patient should already have registered with the health system portal and have the credentials (Currently our application uses Cerner Code platform to do this since the Emory Health portal is not yet ready to deploy applications).
* Once logged in the patient fills in the SDOM questionnaire and submits it.
* The provider/clinician will be able to view the patient data and various statistics associated with that data by logging into the _Provider portal_ and selecting the patient to view. 

=== Details of the application:
* The application is currently hosted in Georgia Tech’s HDAP servers. 
* The application can be accessed at https://cs6440-f18-prj32.apps.hdap.gatech.edu/[SDOM Questionnaire Application]
* The `Open SDOM Questionnaire` link is meant for patients and the `Open Dashboard` simulates a provider patient listing.

=== Frequently Asked Questions:

==== How does the SDOM Questionnaire authenticate?
The SDOM Questionnaire application (Patient facing and Clinician facing) is registered with the Cerner Open Developer Experience (code.cerner.com) platform. This platform generates unique ClientIDs for each of the registered applications. It can also generate test data credentials that can be used in our application. The ClientID generated by the platform is used in our application to authenticate the test data credentials provided.

==== How do I login into the _Patient Portal_?
The application is currently hosted in Georgia Tech’s HDAP servers. The patient data being used is obtained from the Cerner Open Developer Experience (code.cerner.com) platform by registering our applications there.
Once you login to that portal using a registered email id (teameasternfhircoders@gmail.com / Fhirc0ders in this case), you will be presented with the HDAP patient application.

.To get a patient login credential to our application 
* Log in to https://cernercare.com/accounts/login[Cerner Care] using teameasternfhircoders@gmail.com / Fhirc0ders
* Select the Patient Application (for Patient facing page) 
* Then select `Begin Testing` option
* Select a Patient from the list in the pop-up window and hit `Next`
* Use the displayed set of credentials to login as a Patient at the https://cs6440-f18-prj32.apps.hdap.gatech.edu/form[Patient Questionnaire Page]

==== How do I login into the _Provider or Clinician Dashboard_?
The application displays a Provider dashboard where they can view patient data and statistics.
Currently, the application is set to https://github.gatech.edu/gt-cs6440-hit-fall2018/Remote-capture-of-Standardized-Dermatology-Outcomes-Measures-in-Clinical-Practice/blob/master/Final%20Delivery/Deployment%20Guide.adoc#configuration[DEBUG] configuration which enables access to the Clinician dashboard without authentication. 

In production, the steps to access this dashboard will be similar to the steps to access the _patient portal_ except that the user would have to choose the HDAP Provider App instead of the HDAP Patient App to get the credentials from the Cerner CODE page.

* Select the HDAP Provider Application at https://code.cerner.com/developer/smart-on-fhir/apps[Cerner Code Page] (login using teameasternfhircoders@gmail.com / Fhirc0ders)
* Then select `Begin Testing` option
* Choose the "Yes" option to confirm that you do require a patient, choose a patient from the list, scroll to the bottom and hit Next. 
* This gives a set of credentials.
* Click the "Launch" button to launch the dashboard and use the credentials displayed in the last step to login.

==== I am unable to use the patient facing form and the clinician facing page at the same time on different tabs on the web browser. Is something wrong?
This is expected because the sessions generated for the patient and clinician pages are interfering. Please open one of the pages in a normal tab and the other one as an incognito tab and they should work fine at the same time.

==== How can I check the application configuration at code.cerner.com?
The applications - Patient facing and Clinician facing - can be checked by navigating to + 
https://code.cerner.com/developer/smart-on-fhir/apps/ + 
and logging in with the following credentials: + 
Email Address: teameasternfhircoders@gmail.com + 
Password: Fhirc0ders

The following applications will be visible: +
`HDAP Provider App` + 
`HDAP Patient App`

Clicking on any of these will display the details of the corresponding application.

==== What are the scopes used by these applications?
Both HDAP Provider App and HDAP Patient App use:
user/Patient.read scope

==== What programming language is the application written in?
The SDOM Questionnaire application is written in Python, using the Django framework

==== Does this use dstu2 or dstu3?
DSTU2.
